### ISSUE TITLE
GDrive upload fails when a remote folder has spaces within its name.

### ISSUE THREAD

**Issue by FherStk** [FherStk/AutoCheck#60]
**Example:**
```
name: "Generic Google Drive Content Importer"

pre:
  - extract:   
      file: "*.zip"              
      recursive: !!bool True
      remove: !!bool True 

  - upload_gdrive:      
      source: "*.txt"   
      remove: !!bool False
      recursive: !!bool True   
      link: !!bool True        
      copy: !!bool True
      remote_path: "\\Curs 2020-2021\\Mòduls Professionals\\DAM M05\\UF2\\NF4\\Lliuraments\\Pràctica 2: Documentació, refacció i proves unitàries"              
      remote_file: "{#^[^_]+(?=_)$CURRENT_FOLDER_NAME}"

batch: 
  - caption: "Running on batch mode for ~{#^[^_]+(?=_)$CURRENT_FOLDER_NAME}:"       
  - local:                             
      - path: "C:\\Users\\fher\\Downloads\\DAM2M05"

output:
  pause: False
```

**Output:**
```
 Uploading files to Google Drive: 
      Checking the local file video.txt:
         ERROR:
            -Object reference not set to an instance of an object.

```
